"""users

Revision ID: 86d4ca7bf1ec
Revises: 
Create Date: 2019-11-27 09:22:03.814196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d4ca7bf1ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_constraint('pok_id', 'base_stats', type_='foreignkey')
    op.create_foreign_key('pok_id', 'base_stats', 'pokemon', ['pok_id'], ['pok_id'], source_schema='ka7619', referent_schema='ka7619')
    op.drop_constraint('poke_fk', 'pokemon_evolution_matchup', type_='foreignkey')
    op.create_foreign_key('poke_fk', 'pokemon_evolution_matchup', 'pokemon', ['pok_id'], ['pok_id'], source_schema='ka7619', referent_schema='ka7619')
    op.drop_constraint('pokemon_moves_ibfk_2', 'pokemon_moves', type_='foreignkey')
    op.drop_constraint('pokemon_moves_ibfk_1', 'pokemon_moves', type_='foreignkey')
    op.create_foreign_key('pokemon_moves_ibfk_2', 'pokemon_moves', 'moves', ['move_id'], ['move_id'], source_schema='ka7619', referent_schema='ka7619')
    op.create_foreign_key('pokemon_moves_ibfk_1', 'pokemon_moves', 'pokemon', ['pok_id'], ['pok_id'], source_schema='ka7619', referent_schema='ka7619')
    op.drop_constraint('damage_type', 'types', type_='foreignkey')
    op.create_foreign_key('damage_type', 'types', 'type_efficacy', ['damage_type_id'], ['damage_type_id'], source_schema='ka7619', referent_schema='ka7619')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('damage_type', 'types', schema='ka7619', type_='foreignkey')
    op.create_foreign_key('damage_type', 'types', 'type_efficacy', ['damage_type_id'], ['damage_type_id'])
    op.drop_constraint('pokemon_moves_ibfk_1', 'pokemon_moves', schema='ka7619', type_='foreignkey')
    op.drop_constraint('pokemon_moves_ibfk_2', 'pokemon_moves', schema='ka7619', type_='foreignkey')
    op.create_foreign_key('pokemon_moves_ibfk_1', 'pokemon_moves', 'pokemon', ['pok_id'], ['pok_id'])
    op.create_foreign_key('pokemon_moves_ibfk_2', 'pokemon_moves', 'moves', ['move_id'], ['move_id'])
    op.drop_constraint('poke_fk', 'pokemon_evolution_matchup', schema='ka7619', type_='foreignkey')
    op.create_foreign_key('poke_fk', 'pokemon_evolution_matchup', 'pokemon', ['pok_id'], ['pok_id'])
    op.drop_constraint('pok_id', 'base_stats', schema='ka7619', type_='foreignkey')
    op.create_foreign_key('pok_id', 'base_stats', 'pokemon', ['pok_id'], ['pok_id'])
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
